<!DOCTYPE HTML>
<!--
	Strongly Typed by HTML5 UP
	html5up.net | @n33co
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<!-- Head -->
	<?php include 'head.php';?>
	<?php $this_page = "solution.php";?>
			<!-- Feature -->
			<div id="features-wrapper">
				<section id="features" class="container">
					<div class="row">
						<div class="2u"></div>
						<div class="8u">
							<br />
							<div style="width:100%;">
								<div style="position:relative;overflow:hidden;margin-left:.5em;float:left;margin-right:2em;">
									<iframe src="https://player.vimeo.com/video/153237279" width="250" height="444.5" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
								</div>
									<p style="font-weight:900;"><i>
									"I have been using the tab[let] daily and the talk back facility is just awesome. Of course I do have a keyboard attached to it as it makes
									typing faster. I am now happy to learn the swipe technique and use the tab with much ease. As it is very convenient to use I now read
									all my stories on Go Read or Darwin Reader. I have started browsing the net and reading news. I wasn’t sure about news at first, but now I
									read a little bit of it. I have also started using Youtube. The best part is now I chat on What’s app with my friends. I feel extremely
									happy that I have this tab which helps me do so much and so fast. It has also helped me increase my knowledge."</i>&nbsp;&nbsp;&nbsp;&mdash; Nisha D'Souza, March, 2015<br />(5th Grade student at St. John's Universal School, Mumbai, India)
									</p>
							</div>
							<div style="width: 100%;clear:both;">
								<p>Our goal is to assist people with Visual Impairment (VI) to join the mainstream learning community. The VI 
								population uses braille and human readers to develop language skills, especially in early childhood. The importance of 
								braille is unquestionable; however, the visually impaired also need the ability to read all of the material 
								available to people with normal sight. In addition to hard copy books, today we get digital information in form of 
								email, documents, spreadsheets, presentations, websites, ebooks, Twitter&#174; and Facebook&#174;. Printing 
								all of these in braille is neither practical nor timely.</p>
								<p>Advances in computing hardware and software technologies have opened new opportunities for the VI population. They 
								can now compete for professional jobs. The enabling technology is Text To Speech (TTS) software that allows people to 
								read electronic text by listening to speech generated by TTS software. <p>
								<p>In PCs, tablets & smartphones, TTS software is the basis of Accessibility Mode for the Visually Impaired. This 
								feature is referred to as "Talkback" on Android, and "Voice Over" on Apple&#174; devices. As of now, Hindi is the only 
								Indian language supported by Android and iOS TTS. (Learn more about the Android TTS 
								<a href="https://play.google.com/store/apps/details?id=com.google.android.tts&hl=en" target="_blank">here</a>.)</p>
								<p>Fortunately, Android allows third party software developers to add support for additional languages or different 
								voices.  We are using this capability to extend the languages supported by Android. This work is being developed under the 
								leadership of Prof. Alan Black at Carnegie Mellon University (CMU).  Prof. Black is a world renowned technologist in language 
								processing. We are leveraging <a href="http://festvox.org" target="_blank">Festvox</a> and 
								<a href="http://www.festvox.org/flite" target="_blank">Flite</a> open source software developed over the last 20 years with contributions 
								from researchers and developers around the world.</p>
								<p><a href="https://play.google.com/store/apps/details?id=edu.cmu.cs.speech.tts.flite&hl=en" target="_blank">FLITE 3.0</a> is available in 
								Google Play Store as a free download.  It is designed to run on low cost Android tablets and Smartphones, such as the MOTO E(6,000/- Indian
								Rupees).  It supports: <span style='font-weight:900;'>Hindi, Marathi, Kannada, Tamil, Gujarati, and Telugu</span>.  Support for 
								<span style='font-weight:900;'>Bengali, Assamese, Oriya, Punjabi, Malayalam and Urdu</span> is planned for later this year.
								<p>You can listen to the speech generated by FLITE TTS on the <a href='http://www.hear2read.org/demo/app.php' target='_blank'>Demo</a> page  
								using the same FLITE code as in the Android App.</p>
								<p>We are looking for volunteers who can integrate it Windows using 
								<a href='https://msdn.microsoft.com/en-us/library/ee125663%28v=vs.85%29.aspx' target='_blank'>Microsoft Speech APIs (SAPI 5.4)</a>.</p>
								<p>This software is used with many applications, including screen readers such as 
								<a href="https://play.google.com/store/apps/details?id=com.google.android.marvin.talkback&hl=en" target="_blank">
								Android Talkback</a> and 
								<a href="https://play.google.com/store/apps/details?id=com.hyperionics.avar&hl=en" target="_blank">
								@Voice Aloud Reader</a>, for reading email, web sites. It is also used in ebook readers that allow navigation within a book by 
								chapter, page number, or bookmark, and word searches. Commonly used ebook readers in the VI population include 
								<a href="https://play.google.com/store/apps/details?id=org.benetech.android" target="_blank">
								Go Read</a>, and 
								<a fref="https://play.google.com/store/apps/details?id=org.geometerplus.zlibrary.ui.android" target="_bland">FBReader&#174;</a> 
								when used with the <a href="https://play.google.com/store/apps/details?id=com.hyperionics.fbreader.plugin.tts_plus" target="_blank">
								TTS+ plug-in</a>.</p>
							</div>
						</div>
						<div class="u2"></div>
					</div>
				</section>
			</div>
		<!-- Footer -->
		<?php include 'footer.php';?>
	</body>
</html>