<!DOCTYPE HTML>
<!--
	Strongly Typed by HTML5 UP
	html5up.net | @n33co
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<!-- Head -->
	<?php include 'head.php';?>
	<?php $this_page = "solution.php";?>
			<!-- Feature -->
			<div id="features-wrapper">
				<section id="features" class="container">
					<div class="row">
						<div class="2u"></div>
						<div class="8u">
							<br />
							<div style="width:100%;">
								<div style="position:relative;overflow:hidden;margin-left:.5em;float:left;margin-right:2em;">
									<iframe src="https://player.vimeo.com/video/143560709" width="250" height="444.5" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
								</div>
									<p style="font-weight:900;"><i>
									"I have been using the tab[let] daily and the talk back facility is just awesome. Of course I do have a keyboard attached to it as it makes
									typing faster. I am now happy to learn the swipe technique and use the tab with much ease. As it is very convenient to use I now read
									all my stories on Go Read or Darwin Reader. I have started browsing the net and reading news. I wasn’t sure about news at first, but now I
									read a little bit of it. I have also started using Youtube. The best part is now I chat on What’s app with my friends. I feel extremely
									happy that I have this tab which helps me do so much and so fast. It has also helped me increase my knowledge."</i>&nbsp;&nbsp;&nbsp;&mdash; Nisha D'Souza, March, 2015<br />(5th Grade student at St. John's Universal School, Mumbai, India)
									</p>
							</div>
							<div style="width: 100%;clear:both;">
								<p>Our goal is to assist people with Visual Impairment (VI) to join the mainstream learning community. The VI 
								population uses braille and human readers to develop language skills, especially in early childhood. The importance of 
								braille is unquestionable; however, the visually impaired also need the ability to read all of the material 
								available to people with normal sight. In addition to hard copy books, today we get digital information in form of 
								email, documents, spreadsheets, presentations, websites, ebooks, Twitter&#174; and Facebook&#174;. Printing 
								all of these in braille is neither practical nor timely.</p>
								<p>Advances in computing hardware and software technologies have opened new opportunities for the VI population. They 
								can now compete for professional jobs. The enabling technology is Text To Speech (TTS) software that allows people to 
								read electronic text by listening to speech generated by TTS software. <p>
								<p>In PCs, tablets & smartphones, TTS software is the basis of Accessibility Mode for the Visually Impaired. This 
								feature is referred to as "Talkback" on Android, and "Voice Over" on Apple&#174; devices. As of now, Hindi is the only 
								Indian language supported by Android and iOS TTS. (Learn more about the Android TTS 
								<a href="https://play.google.com/store/apps/details?id=com.google.android.tts&hl=en" target="_blank">here</a>.)</p>
								<p>Fortunately, Android allows third party software developers to add support for additional languages or different 
								voices (such as a male Hindi voice in addition to the female Hindi voice provided by Google&#174;). We are using this 
								capability to extend the languages supported by Android TTS.</p>
								<p>TTS software for Indian languages is being developed under the leadership of Prof. Alan Black 
								at Carnegie Mellon University (CMU).  Prof. Black is a world renowned technologist in language processing. 
								This software leverages the Festvox open source software framework developed over the last 20 years with contributions 
								from researchers and developers around the world. The Festvox framework is currently capable of supporting the 
								following Indian languages:<br />
								<center style="font-weight:900;">Hindi, Marathi, Tamil, Gujarati, Kannada, Bengali, Assamese, and Telugu</center></p>
								<p>The Hear2Read team is using the Festvox framework to build voice databases and associated rules for these languages. 
								All software developed under this project is open source. It is published by the CMU Language Technology Institute 
								(LTI) on the Festvox website. We are focusing our efforts on developing software for low-cost Android smartphones and 
								tablets, such as the Moto E Smartphone (6,000/- Indian Rupees).</p>
								<p>This software is used with many applications, including screen readers such as 
								<a href="https://play.google.com/store/apps/details?id=com.google.android.marvin.talkback&hl=en" target="_blank">
								Android Talkback</a> and 
								<a href="https://play.google.com/store/apps/details?id=com.hyperionics.avar&hl=en" target="_blank">
								@Voice Aloud Reader</a>, for reading email, web sites. It is also used in ebook readers that allow navigation within a book by 
								chapter, page number, or bookmark, and word searches. Commonly used ebook readers in the VI population include 
								<a href="https://play.google.com/store/apps/details?id=org.benetech.android" target="_blank">
								Go Read</a>, and 
								<a fref="https://play.google.com/store/apps/details?id=org.geometerplus.zlibrary.ui.android" target="_bland">FBReader&#174;</a> 
								when used with the <a href="https://play.google.com/store/apps/details?id=com.hyperionics.fbreader.plugin.tts_plus" target="_blank">
								TTS+ plug-in</a>.</p>
							</div>
						</div>
						<div class="u2"></div>
					</div>
				</section>
			</div>
		<!-- Footer -->
		<?php include 'footer.php';?>
	</body>
</html>